---
- name: "Get the API list of all {{ differential_item.name }} in the Default Organization"
  set_fact:
    controller_api_results: "{{ lookup('awx.awx.controller_api', differential_item.name, query_params={ 'organization': controller_organization_id.id } ,host=controller_hostname, username=controller_username, password=controller_password, verify_ssl=false) }}"

- name: "Find the difference of {{ differential_item.name }} between what is on the Controller versus curated list."
  set_fact:
    set_absent_diff: "{{ lookup('controller_object_diff', api_list=controller_api_results, compare_list=differential_item.differential_test_items, with_present=differential_item.with_present ) }}"

- name: "Assert that the expected {{ differential_item.name }} results match."
  assert:
    that:
      - set_absent_diff ==  differential_item.expected_test_result
...
