---
# list of dicts (or a single dict) describing the Controller settings
controller_settings: []
controller_configuration_settings_secure_logging: "{{ platform_configuration_secure_logging | default('false') }}"
controller_configuration_settings_async_retries: "{{ platform_configuration_async_retries | default(30) }}"
controller_configuration_settings_async_delay: "{{ platform_configuration_async_delay | default(1) }}"
controller_configuration_settings_loop_delay: "{{ controller_configuration_loop_delay | default(0) }}"
platform_configuration_async_dir: null
...
