---
argument_specs:
  main:
    short_description: An Ansible Role to create service nodes on automation platform gateway.
    options:
      routes_list:
        description: Data structure describing your service nodes
        type: list
        required: true
        elements: dict
        options:
          name:
            required: true
            type: str
            description: Name of the resource
          new_name:
            type: str
            description: Setting this option will change the existing name (looked up via the name field)
          description:
            type: str
            description: Description of the service
          gateway_path:
            type: str
            description: |
              Path on the AAP gateway to listen to traffic on
              Required when creating a new Route
          http_port:
            description: |
              Name or ID referencing the Http Port
              Required when creating a new Route
            type: str
          service_cluster:
            description: |
              Name or ID referencing the Service Cluster
              Required when creating a new Route
            type: str
          is_service_https:
            type: bool
            default: false
            description: Set this to true if the service cluster requires HTTPS
          enable_gateway_auth:
            type: bool
            description: If false, the AAP gateway will not insert a gateway token into the proxied request
          service_path:
            type: str
            description: |
              URL path on the AAP Service cluster to route traffic to
              Required when creating a new Route
          service_port:
            type: int
            description: |
              Port on the service to route traffic to
              Required when creating a new Route
          node_tags:
            type: str
            description: |
              Comma separated string
              Selects which (tagged) nodes receive traffic from this route
          state:
            default: "{{ gateway_state | default('present') }}"
            required: false
            type: str
            description: Desired state of the resource.

      # Async variables
      routes_async_retries:
        default: "{{ platform_configuration_async_retries | default(30) }}"
        required: false
        description: This variable sets the number of retries to attempt for the role.
      platform_configuration_async_retries:
        default: 30
        required: false
        description: This variable sets number of retries across all roles as a default.
      routes_async_delay:
        default: "{{ platform_configuration_async_delay | default(1) }}"
        required: false
        description: This variable sets delay between retries for the role.
      platform_configuration_async_delay:
        default: 1
        required: false
        description: This variable sets delay between retries across all roles as a default.
      platform_configuration_async_dir:
        default: null
        required: false
        description: >
          Sets the directory to write the results file for async tasks.
          The default value is set to `null` which uses the Ansible Default of `~/.ansible_async`.


      # No_log variables
      routes_secure_logging:
        default: "{{ platform_configuration_secure_logging | default(false) }}"
        required: false
        type: bool
        description: >
          Whether or not to include the sensitive tasks from this role in the log.
          Set this value to `true` if you will be providing your sensitive values from elsewhere.
      platform_configuration_secure_logging:
        default: true
        required: false
        type: bool
        description: This variable enables secure logging across all roles as a default.

      # Generic across all roles
      platform_state:
        default: present
        required: false
        description: The state all objects will take unless overridden by object default
        type: str
      platform_hostname:
        default: None
        required: false
        description: URL to the Ansible Automation Platform Server.
        type: str
      platform_validate_certs:
        default: true
        required: false
        description: Whether or not to validate the Ansible Automation Platform Server's SSL certificate.
        type: str
      platform_username:
        default: None
        required: false
        description: Admin User on the Ansible Automation Platform Server. Either username / password or oauthtoken need to be specified.
        type: str
      platform_password:
        default: None
        required: false
        description: Controller Admin User's password on the Ansible Automation Platform Server. This should be stored in an Ansible Vault at vars/controller-secrets.yml or elsewhere and called from a parent playbook. Either username / password or oauthtoken need to be specified.
        type: str
      platform_token:
        default: None
        required: false
        description: Controller Admin User's token on the Ansible Automation Platform Server. This should be stored in an Ansible Vault at or elsewhere and called from a parent playbook. Either username / password or oauthtoken need to be specified.
        type: str
...
