---
- name: async_role | An async_role block
  block:
    - name: async_role | Managing Roles | Wait for finish the Projects management
      ansible.builtin.async_status:
        jid: "{{ __controller_role_job_async_results_item.ansible_job_id }}"
      register: __controller_role_job_async_result
      until: __controller_role_job_async_result.finished
      retries: "{{ controller_configuration_role_async_retries }}"
      delay: "{{ controller_configuration_role_async_delay }}"
  rescue:
    - name: async_role | Load error details
      ansible.builtin.include_vars:
        file: "{{ __controller_role_job_async_result.results_file }}"
        name: __error_data

    - name: async_role | Show error and stop execution
      when: not collect_logs
      ansible.builtin.fail:
        msg: "error: {{ __error_data['msg'] }}, response: {{ __error_data['response'] | default ('N/A') }}"

    - name: async_role | Building list of not processed roles
      ansible.builtin.set_fact:
        __roles_error_list: "{{ __roles_error_list | default([]) + [
                                                                    {
                                                                     'role': __error_data['invocation']['module_args']['role'] | default(''),
                                                                     'user': __error_data['invocation']['module_args']['user'] | default(''),
                                                                     'users': __error_data['invocation']['module_args']['users'] | default(''),
                                                                     'team': __error_data['invocation']['module_args']['team'] | default(''),
                                                                     'teams': __error_data['invocation']['module_args']['teams'] | default(''),
                                                                     'target_team': __error_data['invocation']['module_args']['target_team'] | default(''),
                                                                     'target_teams': __error_data['invocation']['module_args']['target_teams'] | default(''),
                                                                     'inventory': __error_data['invocation']['module_args']['inventory'] | default(''),
                                                                     'inventories': __error_data['invocation']['module_args']['inventories'] | default(''),
                                                                     'job_template': __error_data['invocation']['module_args']['job_template'] | default(''),
                                                                     'job_templates': __error_data['invocation']['module_args']['job_templates'] | default(''),
                                                                     'workflow': __error_data['invocation']['module_args']['workflow'] | default(''),
                                                                     'workflows': __error_data['invocation']['module_args']['workflows'] | default(''),
                                                                     'credential': __error_data['invocation']['module_args']['credential'] | default(''),
                                                                     'credentials': __error_data['invocation']['module_args']['credentials'] | default(''),
                                                                     'organization': __error_data['invocation']['module_args']['organization'] | default(''),
                                                                     'organizations': __error_data['invocation']['module_args']['organizations'] | default(''),
                                                                     'lookup_organization': __error_data['invocation']['module_args']['lookup_organization'] | default(''),
                                                                     'project': __error_data['invocation']['module_args']['project'] | default(''),
                                                                     'projects': __error_data['invocation']['module_args']['projects'] | default(''),
                                                                     'instance_groups': __error_data['invocation']['module_args']['instance_groups'] | default(''),
                                                                     'error': __error_data['msg'] | default('')
                                                                    }
                                                                   ]
                            }}"
...
