---
- name: async_role | An async_role block
  block:
    - name: async_role | Managing Roles | Wait for finish the Projects management
      ansible.builtin.async_status:
        jid: "{{ __controller_role_job_async_results_item.ansible_job_id }}"
      register: __controller_role_job_async_result
      until: __controller_role_job_async_result.finished
      retries: "{{ controller_configuration_role_async_retries }}"
      delay: "{{ controller_configuration_role_async_delay }}"
  rescue:
    - name: async_role | Load error details
      ansible.builtin.include_vars:
        file: "{{ __controller_role_job_async_result.results_file }}"
        name: __error_data

    - name: async_role | Show error and stop execution
      when: not collect_logs
      ansible.builtin.fail:
        msg: "error: {{ __error_data['msg'] }}, response: {{ __error_data['response'] }}"

    - name: async_role | Building list of not processed roles
      ansible.builtin.set_fact:
        __roles_error_list: "{{ __roles_error_list | default([]) + [
                                                                    {
                                                                     'name': __error_data['invocation']['module_args']['name'] | default(''),
                                                                     'error': __error_data['msg'] | default('')
                                                                    }
                                                                   ]
                            }}"
...
