---
namespace: infra
name: aap_configuration
version: 1.0.0
description: A collection of roles to manage Ansible AAP
readme: README.md
authors:
    - Andrew Huffman
    - Adebisi Oyawale @aoyawale
    - Kedar Kulkarni @kedark3
    - Tom Page @Tompage1994
    - Sean Sullivan @sean-m-sullivan
    - David Danielsson @djdanielsson
repository: https://github.com/redhat-cop/aap_configuration/
issues: https://github.com/redhat-cop/aap_configuration//issues
build_ignore:
    - galaxy.yml.j2
    - release.yml
    - .github
    - '*.tar.gz'
license:
    - GPL-3.0-or-later
tags:
    - aap
    - collection
    - aap_configuration
    - automation_platform
    - infrastructure
...
