---
<<<<<<< HEAD
controller_organizations: []
controller_configuration_organizations_secure_logging: "{{ controller_configuration_secure_logging | default('false') }}"
controller_configuration_organizations_async_retries: "{{ controller_configuration_async_retries | default(30) }}"
controller_configuration_organizations_async_delay: "{{ controller_configuration_async_delay | default(1) }}"
controller_configuration_organizations_loop_delay: "{{ controller_configuration_loop_delay | default(0) }}"
controller_configuration_async_dir: null
controller_configuration_organizations_enforce_defaults: "{{ controller_configuration_enforce_defaults | default(false) }}"
assign_galaxy_credentials_to_org: true
assign_default_ee_to_org: true
assign_notification_templates_to_org: true
assign_instance_groups_to_org: true
=======

# These are the default variables common to most gateway_configuration roles
# You shouldn't need to define them again and again but they should be defined
# gateway_hostname: "{{ inventory_hostname }}"
# gateway_token: ""
# gateway_validate_certs: false

# These are the default variables specific to the license role

# a list of dictionaries describing the organizations
organizations_list: []
organizations_secure_logging: "{{ gateway_configuration_secure_logging | default(false) }}"
organizations_async_retries: "{{ gateway_configuration_async_retries | default(30) }}"
organizations_async_delay: "{{ gateway_configuration_async_delay | default(1) }}"
organizations_enforce_defaults: "{{ gateway_configuration_enforce_defaults | default(false) }}"
>>>>>>> 40b40ddac1c00aac7d878bd41af23a6d562296e5
...
