---
apiVersion: v1
kind: Secret
metadata:
  name: awx-admin-password
  namespace: awx
stringData:
  password: password

kubectl create secret generic awx-admin-password --from-literal=password=password