---
argument_specs:
  main:
    short_description: An Ansible Role to run a list of ad hoc commands on Ansible Controller.
    options:
      controller_bulk_job_launch_commands:
        description: Data structure describing your ad hoc commands to run
        type: list
        elements: dict

      # No_log variables
      controller_configuration_bulk_job_launch_secure_logging:
        default: "{{ platform_configuration_secure_logging | default(false) }}"
        required: false
        type: bool
        description: Whether or not to include the sensitive ad_hoc_command role tasks in the log. Set this value to `true` if you will be providing your sensitive values from elsewhere.
      platform_configuration_secure_logging:
        default: false
        required: false
        type: bool
        description: This variable enables secure logging across all roles as a default.

      # Generic across all roles
      platform_state:
        default: present
        required: false
        description: The state all objects will take unless overridden by object default
        type: str
      platform_hostname:
        default: None
        required: false
        description: URL to the Ansible Automation Platform Server.
        type: str
      platform_validate_certs:
        default: true
        required: false
        description: Whether or not to validate the Ansible Automation Platform Server's SSL certificate.
        type: str
      platform_username:
        default: None
        required: false
        description: Admin User on the Ansible Automation Platform Server. Either username / password or oauthtoken need to be specified.
        type: str
      platform_password:
        default: None
        required: false
        description: Platform Admin User's password on the Server.  This should be stored in an Ansible Vault at vars/platform-secrets.yml or elsewhere and called from a parent playbook.
        type: str
      platform_token:
        default: None
        required: false
        description: Controller Admin User's token on the Ansible Automation Platform Server. This should be stored in an Ansible Vault at or elsewhere and called from a parent playbook. Either username / password or oauthtoken need to be specified.
        type: str
...
