---
- name: async_inventory | An async_inventory block
  block:
    - name: async_inventory | Managing Controller Inventories | Wait for finish the inventories management
      ansible.builtin.async_status:
        jid: "{{ __inventories_job_async_result_item.ansible_job_id }}"
      register: __inventories_job_async_result
      until: __inventories_job_async_result.finished
      retries: "{{ controller_configuration_inventories_async_retries }}"
      delay: "{{ controller_configuration_inventories_async_delay }}"
  rescue:
    - name: async_inventory | Load error details
      ansible.builtin.include_vars:
        file: "{{ __inventories_job_async_result.results_file }}"
        name: __error_data

    - name: async_inventory | Show error and stop execution
      when: not collect_logs
      ansible.builtin.fail:
        msg: "error: {{ __error_data['msg'] }}, response: {{ __error_data['response'] | default ('N/A') }}"

    - name: async_inventory | Building list of not processed inventories
      ansible.builtin.set_fact:
        __inventories_error_list: "{{ __inventories_error_list | default([]) + [
                                                                                {
                                                                                 'name': __error_data['invocation']['module_args']['name'] | default(''),
                                                                                 'error': __error_data['msg'] | default('')
                                                                                }
                                                                               ]
                                  }}"
...
