---
- name: async_notification_template  | An async_notification_template  block
  block:
    - name: async_notification_template  | Managing Controller Notification Templates | Wait for finish the Job Templates management
      ansible.builtin.async_status:
        jid: "{{ __controller_notification_job_async_results_item.ansible_job_id }}"
      register: __controller_notification_job_async_result
      until: __controller_notification_job_async_result.finished
      retries: "{{ controller_configuration_notifications_async_retries }}"
      delay: "{{ controller_configuration_notifications_async_delay }}"

  rescue:

    - name: async_notification_template  | Load error details
      ansible.builtin.include_vars:
        file: "{{ __controller_notification_job_async_result.results_file }}"
        name: __error_data

    - name: async_notification_template  | Show error and stop execution
      when: not collect_logs
      ansible.builtin.fail:
        msg: "error: {{ __error_data['msg'] }}, response: {{ __error_data['response'] }}"

    - name: async_notification_template  | Building list of not processed templates
      ansible.builtin.set_fact:
        __notification_templates_error_list: "{{ __notification_templates_error_list | default([]) + [
                                                                                                      {
                                                                                                       'name': __error_data['invocation']['module_args']['name'] | default(''),
                                                                                                       'error': __error_data['msg'] | default('')
                                                                                                      }
                                                                                                    ]
                                }}"
...
