---
- name: async_schedule | An async_schedule block
  block:
    - name: async_schedule | Managing Schedules | Wait for finish the schedules management
      ansible.builtin.async_status:
        jid: "{{ __controller_schedule_job_async_results_item.ansible_job_id }}"
      register: __controller_schedules_job_async_result
      until: __controller_schedules_job_async_result.finished
      retries: "{{ controller_configuration_schedules_async_retries }}"
      delay: "{{ controller_configuration_schedules_async_delay }}"
  rescue:
    - name: async_schedule | Load error details
      ansible.builtin.include_vars:
        file: "{{ __controller_schedules_job_async_result.results_file }}"
        name: __error_data

    - name: async_schedule | Show error and stop execution
      when: not collect_logs
      ansible.builtin.fail:
        msg: "error: {{ __error_data['msg'] }}, response: {{ __error_data['response'] | default ('N/A') }}"

    - name: async_schedule | Building list of not processed schedules
      ansible.builtin.set_fact:
        __schedules_error_list: "{{ __schedules_error_list | default([]) + [
                                                                            {
                                                                             'name': __error_data['invocation']['module_args']['name'] | default(''),
                                                                             'error': __error_data['msg'] | default('')
                                                                            }
                                                                           ]
                                }}"
...
