---
# list of dict to describe Controller notification templates
controller_notifications: []
controller_configuration_notifications_secure_logging: "{{ platform_configuration_secure_logging | default('false') }}"
controller_configuration_notifications_async_retries: "{{ platform_configuration_async_retries | default(30) }}"
controller_configuration_notifications_async_delay: "{{ platform_configuration_async_delay | default(1) }}"
controller_configuration_notifications_loop_delay: "{{ controller_configuration_loop_delay | default(0) }}"
platform_configuration_async_dir: null
controller_configuration_notifications_enforce_defaults: "{{ controller_configuration_enforce_defaults | default(false) }}"
...
