---
eda_decision_environments: []

eda_configuration_decision_environment_secure_logging: "{{ platform_configuration_secure_logging | default(false) }}"
eda_configuration_decision_environment_async_retries: "{{ platform_configuration_async_retries | default(50) }}"
eda_configuration_decision_environment_async_delay: "{{ platform_configuration_async_delay| default(1) }}"
platform_configuration_async_dir: null
...
