---
- name: Block for removing old content
  block:
    - name: Pull Current execution_environment
      uri:
        url: "{{ controller_hostname | default(omit, true) }}/api/v2/execution_environment/"
        method: GET
        return_content: true
        body_format: json
        status_code: [200, 202]
        force_basic_auth: true
        user: "{{ controller_username | default(omit, true) }}"
        password: "{{ controller_password | default(omit, true) }}"
        validate_certs: "{{ controller_validate_certs | default(omit) }}"
      register: r_current_execution_environment

    - name: Get differences
      set_fact:
        execution_environment_difference: "{{ _execution_environment_in_controller | difference(_execution_environment_in_code) }}"
      vars:
        _execution_environment_in_controller: "{{ r_current_execution_environment.json.results | json_query(_query2) }}"
        _query2: "[].name"
        _execution_environment_in_code: "{{ controller_execution_environment | json_query(_query1) }}"
        _query1: "[].name"

    - name: Temp add items to list with state absent
      set_fact:
        controller_execution_environment: "{{ (controller_execution_environment | default([])) + [{'name': item, 'state': 'absent'}] }}"
      loop: "{{ execution_environment_difference }}"
  when: execution_environment_auto_remove_old or auto_remove_all_old

# Create Controller Execution Environments
- name: Add Controller Execution Environments
  execution_environment:
    name:                           "{{ __execution_environments_item.name | mandatory }}"
    description:                    "{{ __execution_environments_item.description | default(omit, true) }}"
    image:                          "{{ __execution_environments_item.image | mandatory }}"
    organization:                   "{{ __execution_environments_item.organization.name | default( __execution_environments_item.organization | default(omit, true)) }}"
    credential:                     "{{ __execution_environments_item.credential | default(omit, true) }}"
    pull:                           "{{ __execution_environments_item.pull | default(omit, true) }}"
    state:                          "{{ __execution_environments_item.state | default(controller_state | default('present')) }}"

    # Role specific options
    controller_username:            "{{ controller_username | default(omit, true) }}"
    controller_password:            "{{ controller_password | default(omit, true) }}"
    controller_oauthtoken:          "{{ controller_oauthtoken | default(omit, true) }}"
    controller_host:                "{{ controller_hostname | default(omit, true) }}"
    controller_config_file:         "{{ controller_config_file | default(omit, true) }}"
    validate_certs:                 "{{ controller_validate_certs | default(omit) }}"
  loop: "{{ controller_execution_environments }}"
  loop_control:
    loop_var: "__execution_environments_item"
  no_log: "{{ controller_configuration_execution_environments_secure_logging }}"
  when: controller_execution_environments is defined
...
