---
- name: Block for removing old content
  block:
    - name: Pull Current credential_types
      uri:
        url: "{{ controller_hostname | default(omit, true) }}/api/v2/credential_types/"
        method: GET
        return_content: true
        body_format: json
        status_code: [200, 202]
        force_basic_auth: true
        user: "{{ controller_username | default(omit, true) }}"
        password: "{{ controller_password | default(omit, true) }}"
        validate_certs: "{{ controller_validate_certs | default(omit) }}"
      register: r_current_credential_types

    - name: Get differences
      set_fact:
        credential_types_difference: "{{ _credential_types_in_controller | difference(_credential_types_in_code) }}"
      vars:
        _credential_types_in_controller: "{{ r_current_credential_types.json.results | json_query(_query2) }}"
        _query2: "[].name"
        _credential_types_in_code: "{{ controller_credential_types | json_query(_query1) }}"
        _query1: "[].name"

    - name: Temp add items to list with state absent
      set_fact:
        controller_credential_types: "{{ (controller_credential_types | default([])) + [{'name': item, 'state': 'absent'}] }}"
      loop: "{{ credential_types_difference }}"
  when: credential_types_auto_remove_old or auto_remove_all_old

- name: Add Credential Types
  credential_type:
    name:                           "{{ __controller_credential_type_item.name | mandatory }}"
    description:                    "{{ __controller_credential_type_item.description | default(omit, true) }}"
    injectors:                      "{{ __controller_credential_type_item.injectors | default(omit, true) | regex_replace('[ ]{2,}','') }}"
    inputs:                         "{{ __controller_credential_type_item.inputs | default(omit, true) }}"
    kind:                           "{{ __controller_credential_type_item.kind | default(omit, true) }}"
    state:                          "{{ __controller_credential_type_item.state | default(controller_state | default('present')) }}"

    # Role specific options
    controller_username:            "{{ controller_username | default(omit, true) }}"
    controller_password:            "{{ controller_password | default(omit, true) }}"
    controller_oauthtoken:          "{{ controller_oauthtoken | default(omit, true) }}"
    controller_host:                "{{ controller_hostname | default(omit, true) }}"
    controller_config_file:         "{{ controller_config_file | default(omit, true) }}"
    validate_certs:                 "{{ controller_validate_certs | default(omit) }}"
  loop: "{{ controller_credential_types }}"
  loop_control:
    loop_var: __controller_credential_type_item
  no_log: "{{ controller_configuration_credential_types_secure_logging }}"
...
