---
- name: "Run the following infra.controller_configuration roles: {{ controller_configuration_dispatcher_roles | map(attribute='role') | join(', ') }}"
  ansible.builtin.include_role:
    name: "{{ __role.role }}"
    apply:
      tags: "{{ __role.tags }}"
  when: vars[__role.var] is defined
  tags: always
  loop: "{{ controller_configuration_dispatcher_roles }}"
  loop_control:
    loop_var: __role
  vars:
    assign_galaxy_credentials_to_org: "{{ __role.assign_galaxy_credentials_to_org | default(false) }}"
    assign_default_ee_to_org: "{{ __role.assign_default_ee_to_org | default(false) }}"
...
