---
- name: Block for removing old content
  block:
    - name: Pull Current users
      uri:
        url: "{{ controller_hostname | default(omit, true) }}/api/v2/users/"
        method: GET
        return_content: true
        body_format: json
        status_code: [200, 202]
        force_basic_auth: true
        user: "{{ controller_username | default(omit, true) }}"
        password: "{{ controller_password | default(omit, true) }}"
        validate_certs: "{{ controller_validate_certs | default(omit) }}"
      register: r_current_users

    - name: Get differences
      set_fact:
        users_difference: "{{ _users_in_controller | difference(_users_in_code) }}"
      vars:
        _users_in_controller: "{{ r_current_users.json.results | json_query(_query2) }}"
        _query2: "[].name"
        _users_in_code: "{{ controller_users | json_query(_query1) }}"
        _query1: "[].name"

    - name: Temp add items to list with state absent
      set_fact:
        controller_users: "{{ (controller_users | default([])) + [{'name': item, 'state': 'absent'}] }}"
      loop: "{{ users_difference }}"
  when: users_auto_remove_old or auto_remove_all_old

- name: Add controller user
  user:
    username:                 "{{ __controller_user_accounts_item.user | default(__controller_user_accounts_item.username) | mandatory }}"
    # the 'true' in the second default leads to no password being set if the default password is empty
    password:                 "{{ __controller_user_accounts_item.password | default(controller_user_default_password | default(omit, true)) }}"
    email:                    "{{ __controller_user_accounts_item.email | default(omit, true) }}"
    first_name:               "{{ __controller_user_accounts_item.firstname | default(__controller_user_accounts_item.first_name | default(omit, true)) }}"
    last_name:                "{{ __controller_user_accounts_item.lastname | default(__controller_user_accounts_item.last_name | default(omit, true)) }}"
    is_superuser:             "{{ __controller_user_accounts_item.is_superuser | default(__controller_user_accounts_item.superuser | default(omit)) }}"
    is_system_auditor:        "{{ __controller_user_accounts_item.is_auditor | default(__controller_user_accounts_item.is_system_auditor | default(omit)) }}"
    update_secrets:           "{{ __controller_user_accounts_item.update_secrets | default(omit) }}"
    state:                    "{{ __controller_user_accounts_item.state | default(controller_state | default(omit, true)) }}"

    # Role Standard Options
    controller_host:          "{{ controller_hostname | default(omit, true) }}"
    controller_username:      "{{ controller_username | default(omit, true) }}"
    controller_password:      "{{ controller_password | default(omit, true) }}"
    controller_oauthtoken:    "{{ controller_oauthtoken | default(omit, true) }}"
    validate_certs:           "{{ controller_validate_certs | default(omit) }}"
    controller_config_file:   "{{ controller_config_file | default(omit, true) }}"
  loop: "{{ controller_user_accounts }}"
  loop_control:
    loop_var: __controller_user_accounts_item
  no_log: "{{ controller_configuration_users_secure_logging }}"
...
