---
# list of dicts describing Controller users
controller_user_accounts: []
# if you're too lazy to give your users a password, this is the default they will get
# set this variable to something false and there won't be a default password
controller_user_default_password: "change_me"

controller_configuration_users_secure_logging: "{{ platform_configuration_secure_logging | default('true') }}"
controller_configuration_users_async_retries: "{{ platform_configuration_async_retries | default(30) }}"
controller_configuration_users_async_delay: "{{ platform_configuration_async_delay | default(1) }}"
controller_configuration_users_loop_delay: "{{ controller_configuration_loop_delay | default(0) }}"
platform_configuration_async_dir: null
controller_configuration_users_enforce_defaults: "{{ controller_configuration_enforce_defaults | default(false) }}"
...
