---
- name: "Get current Team Roles from the API"
  ansible.builtin.set_fact:
    team_roles_lookvar: "{{ query(controller_api_plugin, 'api/v2/teams/' + teamid + '/roles/',
                                  host=controller_hostname, oauth_token=controller_oauthtoken, verify_ssl=controller_validate_certs,
                                  return_all=true, max_objects=query_controller_api_max_objects)
                         }}"
  no_log: "{{ controller_configuration_filetree_create_secure_logging }}"

- name: "Block for to generate flatten output"
  when:
    - flatten_output is defined
    - flatten_output | bool
  block:
    - name: "Stat if the output file exists"
      ansible.builtin.stat:
        path: "{{ output_path }}/team_roles.yaml"
      register: team_roles_file

    - name: "Add current team roles to the team roles flat file"
      blockinfile:
        create: true
        insertafter: EOF
        path: "{{ __dest }}"
        marker: ""
        block: "{{ lookup('template', 'templates/current_team_roles.j2') }}"
      vars:
        current_team_roles_asset_value: "{{ team_roles_lookvar }}"
        __dest: "{{ output_path }}/team_roles.yaml"
        first_team_role: "{{ not team_roles_file.stat.exists }}"
      when: team_roles_lookvar | length > 0

- name: "Block for to generate the filetre_create normal output"
  when: flatten_output is not defined or (flatten_output | bool) == false
  block:
    - name: "Create the output directory for team roles: {{ output_path }}"
      ansible.builtin.file:
        path: "{{ output_path }}/team_roles"
        state: directory
        mode: '0755'

    - name: "Add current roles to the output yaml file"
      ansible.builtin.template:
        src: "templates/current_team_roles.j2"
        dest: "{{ output_path }}/team_roles/current_roles_{{ teamname | regex_replace('/', '_') }}.yaml"
        mode: '0644'
      vars:
        current_team_roles_asset_value: "{{ team_roles_lookvar }}"
      when: team_roles_lookvar | length > 0
...
