---
- name: Block for removing old content
  ansible.builtin.block:
    - name: Pull Current teams
      ansible.builtin.uri:
        url: "{{ controller_hostname | default(omit, true) }}/api/v2/teams/"
        method: GET
        return_content: true
        body_format: json
        status_code: [200, 202]
        force_basic_auth: true
        user: "{{ controller_username | default(omit, true) }}"
        password: "{{ controller_password | default(omit, true) }}"
        validate_certs: "{{ controller_validate_certs | default(omit) }}"
      register: r_current_teams

    - name: Get differences
      ansible.builtin.set_fact:
        teams_difference: "{{ _teams_in_controller | difference(_teams_in_code) }}"
      vars:
        _teams_in_controller: "{{ r_current_teams.json.results | json_query(_query2) }}"
        _query2: "[].name"
        _teams_in_code: "{{ controller_teams | json_query(_query1) }}"
        _query1: "[].name"

    - name: Temp add items to list with state absent
      ansible.builtin.set_fact:
        controller_teams: "{{ (controller_teams | default([])) + [{'name': item, 'state': 'absent'}] }}"
      loop: "{{ teams_difference }}"
  when: teams_auto_remove_old

- name: Create Ansible Controller Team
  team:
    name:                     "{{ __controller_team_item.name | mandatory }}"
    new_name:                 "{{ __controller_team_item.new_name | default(omit, true) }}"
    description:              "{{ __controller_team_item.description | default(omit, true) }}"
    organization:             "{{ __controller_team_item.organization.name | default( __controller_team_item.organization ) | mandatory }}"
    state:                    "{{ __controller_team_item.state | default(controller_state | default('present')) }}"

    # Role Standard Options
    controller_config_file:   "{{ controller_config_file | default(omit, true) }}"
    controller_host:          "{{ controller_hostname | default(omit, true) }}"
    controller_password:      "{{ controller_password | default(omit, true) }}"
    controller_username:      "{{ controller_username | default(omit, true) }}"
    controller_oauthtoken:    "{{ controller_oauthtoken | default(omit, true) }}"
    validate_certs:           "{{ controller_validate_certs | default(omit) }}"
  loop: "{{ controller_teams }}"
  loop_control:
    loop_var: __controller_team_item
  no_log: "{{ controller_configuration_teams_secure_logging }}"
...
