---

# These are the default variables common to most ah_configuration roles
# You shouldn't need to define them again and again but they should be defined
# ah_hostname: "{{ inventory_hostname }}"
# ah_oauthtoken: ""
# platform_validate_certs: false

# These are the default variables specific to the license role
ah_configuration_collection_repository_secure_logging: "{{ platform_configuration_secure_logging | default(false) }}"
ah_configuration_collection_repository_async_timeout: "{{ platform_configuration_async_timeout | default(1000) }}"
ah_configuration_collection_repository_async_retries: "{{ platform_configuration_async_retries | default(50) }}"
ah_configuration_collection_repository_async_delay: "{{ platform_configuration_async_delay | default(1) }}"
platform_configuration_async_dir: null
...
