---
- name: async_inventory_source | An async_inventory_source block
  block:
    - name: async_inventory_source | Managing Controller Inventory Sources | Wait for finish the inventory_sources management
      ansible.builtin.async_status:
        jid: "{{ __inventory_source_job_async_results_item.ansible_job_id }}"
      register: __inventory_source_job_async_result
      until: __inventory_source_job_async_result.finished
      retries: "{{ controller_configuration_inventory_sources_async_retries }}"
      delay: "{{ controller_configuration_inventory_sources_async_delay }}"
  rescue:
    - name: async_inventory_source | Load error details
      ansible.builtin.include_vars:
        file: "{{ __inventory_source_job_async_result.results_file }}"
        name: __error_data

    - name: async_inventory_source | Show error and stop execution
      when: not collect_logs
      ansible.builtin.fail:
        msg: "error: {{ __error_data['msg'] }}, response: {{ __error_data['response'] | default ('N/A') }}"

    - name: async_inventory_source | Building list of not processed inventories
      ansible.builtin.set_fact:
        __inventory_sources_error_list: "{{ __inventory_source_error_list | default([]) + [
                                                                                           {
                                                                                            'name': __error_data['invocation']['module_args']['name'] | default(''),
                                                                                            'inventory': __error_data['invocation']['module_args']['inventory'] | default(''),
                                                                                            'type': 'create issue',
                                                                                            'error': __error_data['msg'] | default('')
                                                                                           }
                                                                                          ]
                                        }}"
...
