---
- name: async_execution_environment | An async_execution_environment block
  block:
    - name: async_execution_environment | Managing Controller Execution Environments | Wait for finish the credential_types management
      ansible.builtin.async_status:
        jid: "{{ __execution_environments_job_async_result_item.ansible_job_id }}"
      register: __execution_environments_job_async_result
      until: __execution_environments_job_async_result.finished
      retries: "{{ controller_configuration_execution_environments_async_retries }}"
      delay: "{{ controller_configuration_execution_environments_async_delay }}"
  rescue:
    - name: async_execution_environment | Load error details
      ansible.builtin.include_vars:
        file: "{{ __execution_environments_job_async_result.results_file }}"
        name: __error_data

    - name: async_execution_environment | Show error and stop execution
      when: not collect_logs
      ansible.builtin.fail:
        msg: "error: {{ __error_data['msg'] }}, response: {{ __error_data['response'] | default ('N/A') }}"

    - name: async_execution_environment | Building list of not processed credential_types
      ansible.builtin.set_fact:
        __execution_environment_error_list: "{{ __execution_environment_error_list | default([]) + [
                                                                                              {
                                                                                               'name': __error_data['invocation']['module_args']['name'] | default(''),
                                                                                               'error': __error_data['msg'] | default('')
                                                                                              }
                                                                                             ]
                                            }}"
...
