---
- name: "Gets current Organizations configured"
  ansible.builtin.set_fact:
    __controller_api_organizations: "{{ query(controller_api_plugin, 'organizations',
      host=controller_hostname, oauth_token=controller_oauthtoken, verify_ssl=controller_validate_certs) }}"

- name: "Find the difference of Organizations between what is on the Controller versus curated list."
  ansible.builtin.set_fact:
    __organizations_difference: "{{ lookup('redhat_cop.controller_configuration.controller_object_diff',
                                            api_list=__controller_api_organizations, compare_list=controller_organizations,
                                            with_present=false, set_absent=true)
                                 }}"

- name: "Sets Organization differences"
  ansible.builtin.set_fact:
    controller_organizations: "{{ __organizations_difference }}"
...
