---
- name: Block for removing old content
  ansible.builtin.block:
    - name: Pull Current notification_templates
      ansible.builtin.uri:
        url: "{{ controller_hostname | default(omit, true) }}/api/v2/notification_templates/"
        method: GET
        return_content: true
        body_format: json
        status_code: [200, 202]
        force_basic_auth: true
        user: "{{ controller_username | default(omit, true) }}"
        password: "{{ controller_password | default(omit, true) }}"
        validate_certs: "{{ controller_validate_certs | default(omit) }}"
      register: r_current_notification_templates

    - name: Get differences
      ansible.builtin.set_fact:
        notification_templates_difference: "{{ _notification_templates_in_controller | difference(_notification_templates_in_code) }}"
      vars:
        _notification_templates_in_controller: "{{ r_current_notification_templates.json.results | json_query(_query2) }}"
        _query2: "[].name"
        _notification_templates_in_code: "{{ controller_notification_templates | json_query(_query1) }}"
        _query1: "[].name"

    - name: Temp add items to list with state absent
      ansible.builtin.set_fact:
        controller_notification_templates: "{{ (controller_notification_templates | default([])) + [{'name': item, 'state': 'absent'}] }}"
      loop: "{{ notification_templates_difference }}"
  when: notification_templates_auto_remove_old

- name: Add Controller notifications
  notification_template:
    name:                           "{{ __controller_notification_item.name | mandatory }}"
    new_name:                       "{{ __controller_notification_item.new_name | default(omit, true) }}"
    copy_from:                      "{{ __controller_notification_item.copy_from | default(omit, true) }}"
    description:                    "{{ __controller_notification_item.description | default(omit, true) }}"
    organization:                   "{{ __controller_notification_item.organization.name | default( __controller_notification_item.organization ) }}"
    notification_type:              "{{ __controller_notification_item.notification_type }}"
    notification_configuration:     "{{ __controller_notification_item.notification_configuration }}"
    messages:                       "{{ __controller_notification_item.messages | default(omit, true) | regex_replace('[ ]{2,}','') }}"
    state:                          "{{ __controller_notification_item.state | default(controller_state | default('present')) }}"

    # Role Standard Options
    controller_host:                "{{ controller_hostname | default(omit, true) }}"
    controller_username:            "{{ controller_username | default(omit, true) }}"
    controller_password:            "{{ controller_password | default(omit, true) }}"
    controller_oauthtoken:          "{{ controller_oauthtoken | default(omit, true) }}"
    controller_config_file:         "{{ controller_config_file | default(omit, true) }}"
    validate_certs:                 "{{ controller_validate_certs | default(omit) }}"
  loop: "{{ controller_notifications }}"
  loop_control:
    loop_var: __controller_notification_item
  no_log: "{{ controller_configuration_notifications_secure_logging }}"
...
