---
- name: Determine if filetree_controller_inventories is a string or list
  ansible.builtin.set_fact:
    __filetree_controller_inventories: "{{ [filetree_controller_inventories] if filetree_controller_inventories is string else filetree_controller_inventories }}"

- name: "Get list of files"
  ansible.builtin.find:
    paths: "{{ __filetree_controller_inventories_item }}"
    file_type: file
    recurse: true
  loop: "{{ __filetree_controller_inventories }}"
  loop_control:
    loop_var: __filetree_controller_inventories_item
  register: __list_files_controller_inventories

- name: Extract file paths using json_query
  ansible.builtin.set_fact:
    __list_files_controller_inventories: "{{ __list_files_controller_inventories | json_query('results[].files[].path') }}"

- name: "Read Inventories definitions"
  ansible.builtin.include_vars:
    file: "{{ __read_inventories_definitions_item }}"
  loop: "{{ __list_files_controller_inventories }}"
  loop_control:
    loop_var: __read_inventories_definitions_item
  register: __contents_filetree_controller_inventories
  failed_when: "'VARIABLE IS NOT DEFINED' in __contents_filetree_controller_inventories"

- name: "Set Inventories Data Structure"
  ansible.builtin.set_fact:
    controller_inventories: >-
      {{
        __contents_filetree_controller_inventories.results |
        rejectattr('ansible_facts.controller_inventories', 'undefined') |
        map(attribute='ansible_facts.controller_inventories') |
        ansible.builtin.flatten
      }}
  no_log: "{{ controller_configuration_filetree_read_secure_logging }}"
  when: __contents_filetree_controller_inventories.results
...
