---
- name: Block for removing old content
  block:
    - name: Pull Current inventories
      uri:
        url: "{{ controller_hostname | default(omit, true) }}/api/v2/inventories/"
        method: GET
        return_content: true
        body_format: json
        status_code: [200, 202]
        force_basic_auth: true
        user: "{{ controller_username | default(omit, true) }}"
        password: "{{ controller_password | default(omit, true) }}"
        validate_certs: "{{ controller_validate_certs | default(omit) }}"
      register: r_current_inventories

    - name: Get differences
      set_fact:
        inventories_difference: "{{ _inventories_in_controller | difference(_inventories_in_code) }}"
      vars:
        _inventories_in_controller: "{{ r_current_inventories.json.results | json_query(_query2) }}"
        _query2: "[].name"
        _inventories_in_code: "{{ controller_inventories | json_query(_query1) }}"
        _query1: "[].name"

    - name: Temp add items to list with state absent
      set_fact:
        controller_inventories: "{{ (controller_inventories | default([])) + [{'name': item, 'state': 'absent'}] }}"
      loop: "{{ inventories_difference }}"
  when: inventories_auto_remove_old or auto_remove_all_old

- name: Create inventory
  inventory:
    name:                       "{{ __controller_inventory_item.name | mandatory }}"
    copy_from:                  "{{ __controller_inventory_item.copy_from | default(omit, true) }}"
    description:                "{{ __controller_inventory_item.description | default(omit, true) }}"
    organization:               "{{ __controller_inventory_item.organization.name | default( __controller_inventory_item.organization ) | mandatory }}"
    instance_groups:            "{{ __controller_inventory_item.instance_groups | default(omit, true) }}"
    variables:                  "{{ __controller_inventory_item.variables | default(omit, true) | regex_replace('[ ]{2,}','') }}"
    kind:                       "{{ __controller_inventory_item.kind | default(omit, true) }}"
    host_filter:                "{{ __controller_inventory_item.host_filter | default(omit, true) }}"
    state:                      "{{ __controller_inventory_item.state | default(controller_state | default('present')) }}"

    # Role Standard Options
    controller_config_file:     "{{ controller_config_file | default(omit, true) }}"
    controller_host:            "{{ controller_hostname | default(omit, true) }}"
    controller_username:        "{{ controller_username | default(omit, true) }}"
    controller_password:        "{{ controller_password | default(omit, true) }}"
    controller_oauthtoken:      "{{ controller_oauthtoken | default(omit, true) }}"
    validate_certs:             "{{ controller_validate_certs | default(omit) }}"
  loop: "{{ controller_inventories }}"
  loop_control:
    loop_var: __controller_inventory_item
  no_log: "{{ controller_configuration_inventories_secure_logging }}"
...
