---
# This workflow action will run pre-commit, which will execute ansible and yaml linting
# See .pre-commit-config.yaml for what hooks are executed
name: Release

on:
  release:
    types:
      - published

jobs:
  release:
    uses: "sean-m-sullivan/ansible_collections_tooling/.github/workflows/release_pipeline_single.yml@main"
    with:
      collection_namespace: sean_m_sullivan
      collection_name: controller_configuration
      collection_version: ${{ github.ref_name }}
      collection_repo: https://github.com/redhat-cop/controller_configuration/
      quay_username: redhat_cop
      collection_dependencies: awx.awx
    secrets:
      galaxy_api_key: ${{ secrets.ANSIBLE_GALAXY_APIKEY }}
      token: ${{ secrets.GITHUB_TOKEN }}
      quay_token: ${{ secrets.quay_token }}
...
